# Generated by Django 5.0.2 on 2024-02-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('Buyer', 'Buyer'), ('Seller', 'Seller')], max_length=100),
        ),
    ]
